BiblioJuegos/Controllers/CategoriaController.cs
using BiblioJuegos.BOL;
using BiblioJuegos.DAL.IRepo;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using BiblioJuegos.ViewModels.CategoriaVM;
using ReflectionIT.Mvc.Paging;

namespace BiblioJuegos.Controllers
{
    public class CategoriaController : Controller
    {
        private ICategoriaRepo _repo;

        public CategoriaController(ICategoriaRepo repo) => _repo = repo;

        [HttpGet]
        public async Task<IActionResult> Index(int page  = 1)
        {
            var categorias = _repo.OrdenarPorNombre();

            var categoriasLista = (IOrderedQueryable<CategoriaVMIndex>) categorias.Select(x => new CategoriaVMIndex()
            {
                Id = x.Id,
                Nombre = x.Nombre,
                ImagenURL = x.ImagenURL,
                Descripcion = x.Descripcion
            });
            var modeloARetornar = await PagingList.CreateAsync(categoriasLista, 5, page);

            return View(modeloARetornar);
        }

        [HttpGet]
        public IActionResult Agregar() => View();

        [HttpPost]
        public async Task<IActionResult> Agregar(CategoriaVMIndex categoriaVM)
        {
            if (ModelState.IsValid)
            {
                var categoria = new Categoria()
                {
                    Nombre = categoriaVM.Nombre,
                    Descripcion = categoriaVM.Descripcion,
                    ImagenURL = categoriaVM.ImagenURL
                };

                await _repo.Agregar(categoria);
                return RedirectToAction("Index");
            }
            return View(categoriaVM);
        }

        [HttpGet]
        public async Task<IActionResult> Actualizar(int id)
        {
            var categoria = await _repo.ObtenerPorId(id);

            var categoriaViwModel = new CategoriaVMIndex()
            {
                Id = categoria.Id,
                Nombre = categoria.Nombre,
                Descripcion = categoria.Descripcion,
                ImagenURL = categoria.ImagenURL
            };
            return View(categoriaViwModel);
        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(CategoriaVMIndex categoriaVM)
        {
            if (ModelState.IsValid)
            {
                var categoria = new Categoria
                {
                    Id = categoriaVM.Id,
                    Nombre = categoriaVM.Nombre,
                    Descripcion = categoriaVM.Descripcion,
                    ImagenURL = categoriaVM.ImagenURL
                };
                await _repo.Actualizar(categoria);

                return RedirectToAction("Index");
            }

            return View(categoriaVM);
        }

        [HttpGet]
        public async Task<IActionResult> Detalles(int id)
        {
            var categoria = await _repo.ObtenerPorId(id);

            var categoriaViewModel = new CategoriaVMDetalles()
            {
                Id = categoria.Id,
                Nombre = categoria.Nombre,
                Descripcion = categoria.Descripcion,
                ImagenURL = categoria.ImagenURL,
                AgregadoEn = categoria.AgregadoEn
            };

            return View(categoriaViewModel);
        }

        [HttpGet]



        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                await _repo.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorCategoria"] =
                    "Esta categoría está vinculada con un videojuego. Desvincúlela para eliminarla.";
                return RedirectToAction("Index");
            }
        }
    }
}

BiblioJuegos/Controllers/CompaniaController.cs
using BiblioJuegos.BOL;
using BiblioJuegos.DAL.IRepo;
using BiblioJuegos.ViewModels.CompaniaVM;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace BiblioJuegos.Controllers
{
    public class CompaniaController : Controller
    {
        private readonly ICompaniaRepo _repo;

        public CompaniaController(ICompaniaRepo repo) => _repo = repo;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var companias = await _repo.ObtenerTodas();

            var companiaModel = companias.Select(x => new CompaniaVMIndex()
            {
                Id = x.Id,
                Nombre = x.Nombre,
                Descripcion = x.Descripcion,
                ImagenURL = x.ImagenURL
            });

            return View(companiaModel);
        }

        [HttpGet]
        public IActionResult Agregar() => View();

        [HttpPost]
        public async Task<IActionResult> Agregar(CompaniaVMIndex compania)
        {
            if (ModelState.IsValid)
            {
                var companiaModel = new Compania()
                {
                    Nombre = compania.Nombre,
                    Descripcion = compania.Descripcion,
                    ImagenURL = compania.ImagenURL
                };

                await _repo.Agregar(companiaModel);
                return RedirectToAction("Index");
            }

            return View(compania);
        }

        [HttpGet]
        public async Task<IActionResult> Actualizar(int id)
        {
            var compania = await _repo.ObtenerPorId(id);

            var companiaModel = new CompaniaVMIndex
            {
                Id = compania.Id,
                Nombre = compania.Nombre,
                Descripcion = compania.Descripcion,
                ImagenURL = compania.ImagenURL
            };

            return View(companiaModel);
        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(CompaniaVMIndex compania)
        {
            if (ModelState.IsValid)
            {
                var companiaModel = new Compania()
                {
                    Id = compania.Id,
                    Nombre = compania.Nombre,
                    ImagenURL = compania.ImagenURL,
                    Descripcion = compania.Descripcion
                };

                await _repo.Actualizar(companiaModel);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Detalles(int id)
        {
            var compania = await _repo.ObtenerPorId(id);

            var companiaModel = new CompaniaVMDetalles()
            {
                Id = compania.Id,
                Nombre = compania.Nombre,
                Descripcion = compania.Descripcion,
                ImagenURL = compania.ImagenURL,
                AgregadoEn = compania.AgregadoEn
            };

            return View(companiaModel);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                await _repo.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorCompania"] =
                    "Esta compañía está vinculada con un videojuego. Desvincúlela para eliminarla.";
                return RedirectToAction("Index");
            }
        }
    }
}

BiblioJuegos/Controllers/PlataformaController.cs
using System.Linq;
using System.Threading.Tasks;
using BiblioJuegos.BOL;
using BiblioJuegos.DAL;
using BiblioJuegos.ViewModels.PlataformaVM;
using Microsoft.AspNetCore.Mvc;

namespace BiblioJuegos.Controllers
{
    public class PlataformaController : Controller
    {
        private readonly IPlataformaRepo _repo;

        public PlataformaController(IPlataformaRepo repo) => _repo = repo;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var plataformas = await _repo.ObtenerTodas();

            var plataformaModel = plataformas.Select(x => new PlataformaVMIndex()
            {
                Id = x.Id,
                Nombre = x.Nombre,
                Descripcion = x.Descripcion,
                ImagenURL = x.ImagenURL
            });

            return View(plataformaModel);
        }

        [HttpGet]
        public IActionResult Agregar() => View();

        [HttpPost]
        public async Task<IActionResult> Agregar(PlataformaVMIndex plataforma)
        {
            if (ModelState.IsValid)
            {
                var plataformaModel = new Plataforma()
                {
                    Nombre = plataforma.Nombre,
                    Descripcion = plataforma.Descripcion,
                    ImagenURL = plataforma.ImagenURL
                };

                await _repo.Agregar(plataformaModel);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Actualizar(int id)
        {
            var plataforma = await _repo.ObtenerPorId(id);

            var plataformaModel = new PlataformaVMIndex()
            {
                Id = plataforma.Id,
                Nombre = plataforma.Nombre,
                Descripcion = plataforma.Descripcion,
                ImagenURL = plataforma.ImagenURL
            };

            return View(plataformaModel);
        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(PlataformaVMIndex plataforma)
        {
            if (ModelState.IsValid)
            {
                var plataformaModel = new Plataforma()
                {
                    Id = plataforma.Id,
                    Nombre = plataforma.Nombre,
                    Descripcion = plataforma.Descripcion,
                    ImagenURL = plataforma.ImagenURL
                };
                await _repo.Actualizar(plataformaModel);

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Detalles(int id)
        {
            var plataforma = await _repo.ObtenerPorId(id);

            var plataformaModel = new PlataformaVMDetalles()
            {
                Id = plataforma.Id,
                Nombre = plataforma.Nombre,
                Descripcion = plataforma.Descripcion,
                ImagenURL = plataforma.ImagenURL,
                AgregadoEn = plataforma.AgregadoEn
            };

            return View(plataformaModel);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                await _repo.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorPlataforma"] =
                    "Esta plataforma está vinculada con un videojuego. Desvincúlela para eliminarla.";
                return RedirectToAction("Index");
            }
        }
    }
}

BiblioJuegos/Controllers/VideojuegoController.cs
using BiblioJuegos.BOL;
using BiblioJuegos.DAL;
using BiblioJuegos.DAL.IRepo;
using BiblioJuegos.ViewModels.VideojuegoVM;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace BiblioJuegos.Controllers
{
    public class VideojuegoController : Controller
    {
        private readonly IVideojuegoRepo _videojuegoRepo;
        private readonly ICategoriaRepo _categoriaRepo;
        private readonly ICompaniaRepo _companiaRepo;
        private readonly IPlataformaRepo _plataformaRepo;

        public VideojuegoController(IVideojuegoRepo videojuegoRepo, ICategoriaRepo categoriaRepo, 
            ICompaniaRepo companiaRepo, IPlataformaRepo plataformaRepo)
        {
            _videojuegoRepo = videojuegoRepo;
            _categoriaRepo = categoriaRepo;
            _companiaRepo = companiaRepo;
            _plataformaRepo = plataformaRepo;
        }
       
        [HttpGet]
       public async Task<IActionResult> Index()
        {
            var videojuegosLista = await _videojuegoRepo.ObtenerTodos();

            var videojuegoVM =  videojuegosLista.Select(x => new VideojuegoVMIndex()
            {
                Id = x.Id,
                Titulo = x.Titulo,
                Descripcion = x.Descripcion,
                ImagenURL = x.ImagenURL,
                Lanzamiento = x.Lanzamiento,
                Compania = x.Compania.Nombre,
                Categoria = x.Categoria.Nombre,
                Plataforma = x.Plataforma.Nombre
            });

            return View(videojuegoVM);
        }

        [HttpGet]
        public async Task<IActionResult> Agregar()
        {
            var formulario = new VideojuegoVMFormulario()
            {
                Categorias = await _categoriaRepo.ObtenerTodas(),
                Companias = await _companiaRepo.ObtenerTodas(),
                Plataformas = await _plataformaRepo.ObtenerTodas()
            };

            return View(formulario);
        }

        [HttpPost]
        public async Task<IActionResult> Agregar(VideojuegoVMFormulario formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.Categorias = await _categoriaRepo.ObtenerTodas();
                formulario.Plataformas = await _plataformaRepo.ObtenerTodas();
                formulario.Companias = await _companiaRepo.ObtenerTodas();

                var videojuego = new Videojuego()
                {
                    Titulo = formulario.Titulo,
                    Descripcion = formulario.Descripcion,
                    ImagenURL = formulario.ImagenURL,
                    Lanzamiento = formulario.Lanzamiento,
                    Categoria = formulario.Categorias.FirstOrDefault(x => x.Id == formulario.CategoriaId),
                    Compania = formulario.Companias.FirstOrDefault(x => x.Id == formulario.CompaniaId),
                    Plataforma = formulario.Plataformas.First(x => x.Id == formulario.PlataformaId)
                };

                await _videojuegoRepo.Agregar(videojuego);
                return RedirectToAction("Index");
            }

            return View(formulario);
        }

        [HttpGet]
        public async Task<IActionResult> Actualizar(int id)
        {
            var videojuego = await _videojuegoRepo.ObtenerPorId(id);

            ViewBag.CategoriaSeleccionada = videojuego.Categoria.Nombre;
            ViewBag.CompaniaSeleccionada = videojuego.Compania.Nombre;
            ViewBag.PlataformaSeleccionada = videojuego.Plataforma.Nombre;

            var videojuegoAActualizar = new VideojuegoVMFormulario()
            {
                Id = videojuego.Id,
                Titulo = videojuego.Titulo,
                Descripcion = videojuego.Descripcion,
                ImagenURL = videojuego.ImagenURL,
                Lanzamiento = videojuego.Lanzamiento,
                Categorias = await _categoriaRepo.ObtenerTodas(),
                Companias = await _companiaRepo.ObtenerTodas(),
                Plataformas = await _plataformaRepo.ObtenerTodas()
            };

            return View(videojuegoAActualizar);
        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(VideojuegoVMFormulario formulario)
        {
            if (ModelState.IsValid)
            {
                var videojuego = new Videojuego()
                {
                    Id = formulario.Id,
                    Titulo = formulario.Titulo,
                    Descripcion = formulario.Descripcion,
                    ImagenURL = formulario.ImagenURL,
                    Lanzamiento = formulario.Lanzamiento,
                    Compania = await _companiaRepo.ObtenerPorId(formulario.CompaniaId),
                    Plataforma = await _plataformaRepo.ObtenerPorId(formulario.PlataformaId),
                    Categoria = await _categoriaRepo.ObtenerPorId(formulario.CategoriaId)
                };
                await _videojuegoRepo.Actualizar(videojuego);
                return RedirectToAction("Index");
            }

            return View(formulario);
        }

        [HttpGet]
        public async Task<IActionResult> Detalles(int id)
        {
            var videojuego = await _videojuegoRepo.ObtenerPorId(id);

            var videojuegoModel = new VideojuegoVMDetalles()
            {
                Id = videojuego.Id,
                Titulo = videojuego.Titulo,
                Descripcion = videojuego.Descripcion,
                ImagenURL = videojuego.ImagenURL,
                Lanzamiento = videojuego.Lanzamiento,
                Compania = videojuego.Compania.Nombre,
                Categoria = videojuego.Categoria.Nombre,
                Plataforma = videojuego.Plataforma.Nombre
            };

            return View(videojuegoModel);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                await _videojuegoRepo.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ErrorVideojuego"] = "Error al eliminar videojuego. Vuelva a intentarlo.";
                return RedirectToAction("Index");
            }
        }
    }
}

BiblioJuegos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BiblioJuegos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link
        rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
        crossorigin="anonymous"
    />
    <link href="~/css/alertify.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-gamepad"></i> BiblioJuegos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index"><i class="fas fa-sitemap"></i> Categorías</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compania" asp-action="Index"><i class="fas fa-align-center"></i> Compañías</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plataforma" asp-action="Index"><i class="fas fa-grip-horizontal"></i> Plataformas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Videojuego" asp-action="Index"><i class="fab fa-xbox"></i> Videojuegos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BiblioJuegos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/alertify.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>